# Generated by Django 3.2.8 on 2021-10-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_trv_user', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=300, unique=True)),
                ('f_name', models.CharField(max_length=100, null=True)),
                ('l_name', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=128)),
                ('password_edited_at', models.DateTimeField(auto_now=True, null=True)),
                ('phone_no', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=5)),
                ('appname', models.CharField(max_length=10, null=True)),
                ('register_datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('refer_code', models.TextField(null=True)),
                ('social_type', models.CharField(max_length=45, null=True)),
                ('social_uuid', models.CharField(max_length=300, null=True)),
                ('inctive_user', models.BooleanField()),
            ],
            options={
                'db_table': 'trv_user',
            },
        ),
    ]
