# Generated by Django 3.2.8 on 2021-10-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('seq_wallet_balance', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=60)),
                ('walletID', models.CharField(max_length=65, null=True)),
                ('wallet_balance', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('edited_at', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'db_table': 'wallet_balance',
            },
        ),
    ]
