# Generated by Django 4.0.dev20210810104906 on 2021-10-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('brief', models.CharField(max_length=255)),
                ('title_picture', models.CharField(max_length=255)),
                ('pdfurl', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
